'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Suspense } from 'react';

type SessionData = {
  id: string;
  amount_total: number | null;
  currency: string | null;
  payment_status: string;
  created: number;
  metadata: Record<string, string>;
  customer_details: { email?: string | null; name?: string | null } | null;
};

function formatAmount(amount: number | null, currency: string | null) {
  if (!amount || !currency) return '—';
  return new Intl.NumberFormat('en-GB', { style: 'currency', currency: currency.toUpperCase() }).format(amount / 100);
}

function formatDate(timestamp: number) {
  return new Date(timestamp * 1000).toLocaleString('en-GB', {
    dateStyle: 'long',
    timeStyle: 'short',
  });
}

function PaymentSuccessContent() {
  const searchParams = useSearchParams();
  const sessionId = searchParams.get('session_id');
  const [session, setSession] = useState<SessionData | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    if (!sessionId) { setLoading(false); return; }
    fetch(`/api/payment/session/${sessionId}`)
      .then(r => r.ok ? r.json() : null)
      .then(data => { setSession(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, [sessionId]);

  async function downloadReceipt() {
    if (!session) return;
    setGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });

      const pageW = doc.internal.pageSize.getWidth();
      let y = 20;

      // Header
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(26, 26, 26);
      doc.text('HexaBee', pageW / 2, y, { align: 'center' });
      y += 8;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(107, 114, 128);
      doc.text('Payment Receipt', pageW / 2, y, { align: 'center' });
      y += 12;

      // Divider
      doc.setDrawColor(229, 231, 235);
      doc.line(20, y, pageW - 20, y);
      y += 10;

      // Status badge
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(session.payment_status === 'paid' ? 22 : 107, session.payment_status === 'paid' ? 163 : 114, session.payment_status === 'paid' ? 74 : 128);
      doc.text(session.payment_status === 'paid' ? '✓ Payment Successful' : `Status: ${session.payment_status}`, pageW / 2, y, { align: 'center' });
      y += 14;

      // Amount
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(26, 26, 26);
      doc.text(formatAmount(session.amount_total, session.currency), pageW / 2, y, { align: 'center' });
      y += 16;

      // Divider
      doc.setDrawColor(229, 231, 235);
      doc.line(20, y, pageW - 20, y);
      y += 10;

      // Details table
      const rows: [string, string][] = [
        ['Date', formatDate(session.created)],
        ['Session ID', `...${session.id.slice(-16)}`],
        ['Payment Status', session.payment_status],
      ];

      if (session.metadata?.reference) rows.push(['Reference', session.metadata.reference]);
      if (session.metadata?.receiver || session.metadata?.merchant) {
        rows.push(['Merchant', session.metadata.receiver ?? session.metadata.merchant ?? '']);
      }
      if (session.customer_details?.email) rows.push(['Payer Email', session.customer_details.email]);
      if (session.customer_details?.name) rows.push(['Payer Name', session.customer_details.name]);

      doc.setFontSize(11);
      for (const [label, value] of rows) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(107, 114, 128);
        doc.text(label, 20, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(26, 26, 26);
        // wrap long values
        const lines = doc.splitTextToSize(value, pageW - 80);
        doc.text(lines, pageW - 20, y, { align: 'right' });
        y += 8 * lines.length;
      }

      y += 6;
      doc.setDrawColor(229, 231, 235);
      doc.line(20, y, pageW - 20, y);
      y += 10;

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(156, 163, 175);
      doc.setFont('helvetica', 'normal');
      doc.text('This is an automated payment receipt generated by HexaBee.', pageW / 2, y, { align: 'center' });
      y += 5;
      doc.text('hexabee.buzz', pageW / 2, y, { align: 'center' });

      const filename = `hexabee-receipt-${session.id.slice(-8)}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error('PDF generation failed:', err);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <main style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg)', padding: '24px 16px' }}>
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 20, padding: '36px 32px', maxWidth: 460, width: '100%', boxShadow: '0 4px 24px rgba(0,0,0,0.06)', textAlign: 'center' }}>

        {/* Icon */}
        <div style={{ fontSize: 56, marginBottom: 16 }}>✅</div>

        <h1 style={{ fontSize: 24, fontWeight: 800, margin: '0 0 8px', color: 'var(--text)' }}>Payment successful</h1>
        <p style={{ color: 'var(--muted)', fontSize: 14, margin: '0 0 24px', lineHeight: 1.6 }}>
          Your payment has been processed. The merchant will receive confirmation shortly.
        </p>

        {loading && (
          <p style={{ color: 'var(--muted)', fontSize: 14 }}>Loading receipt details...</p>
        )}

        {!loading && session && (
          <>
            {/* Summary */}
            <div style={{ background: 'var(--bg)', borderRadius: 12, padding: '16px 18px', marginBottom: 20, display: 'flex', flexDirection: 'column', gap: 10, textAlign: 'left' }}>
              <Row label="Amount" value={formatAmount(session.amount_total, session.currency)} />
              <Row label="Date" value={formatDate(session.created)} />
              <Row label="Reference" value={session.metadata?.reference || '—'} />
              <Row label="Merchant" value={session.metadata?.receiver || session.metadata?.merchant || '—'} />
              <Row label="Status" value="Paid ✓" highlight />
            </div>

            {/* Download button */}
            <button
              type="button"
              onClick={downloadReceipt}
              disabled={generating}
              style={{
                width: '100%',
                padding: '14px',
                borderRadius: 12,
                border: 'none',
                background: 'var(--brand)',
                color: '#111',
                fontWeight: 700,
                fontSize: 15,
                cursor: generating ? 'wait' : 'pointer',
                opacity: generating ? 0.7 : 1,
              }}
            >
              {generating ? 'Generating PDF...' : '⬇ Download Receipt'}
            </button>
          </>
        )}

        {!loading && !session && (
          <p style={{ color: 'var(--muted)', fontSize: 14 }}>Receipt details unavailable.</p>
        )}
      </div>
    </main>
  );
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 14, gap: 16 }}>
      <span style={{ color: 'var(--muted)', flexShrink: 0 }}>{label}</span>
      <span style={{ fontWeight: 600, color: highlight ? '#16a34a' : 'var(--text)', textAlign: 'right', wordBreak: 'break-all' }}>{value}</span>
    </div>
  );
}

export default function PaymentSuccessPage() {
  return (
    <Suspense fallback={<main style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>Loading...</main>}>
      <PaymentSuccessContent />
    </Suspense>
  );
}